---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-var
data:
  db_url: "db_host.example.com/my_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      role: webapp
  template:
    metadata:
      labels:
        role: webapp
    spec:
      containers:
        - name: flaskapp
          image: daveyn/devnet:flaskapp3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /container-data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 300Mi
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: data-volume
          hostPath:
            path: /data

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  selector:
    role: webapp
