---
apiVersion: v1
kind: Pod
metadata:
  name: mc-pod
  labels:
    role: webapp
spec:
  containers:
    - name: flaskapp
      image: daveyn/devnet:flaskapp3
      ports:
        - containerPort: 5000
    # The 2nd container could be the same image as the 1st
    # I choose to create a new container listening on a non-default flask port
    - name: flaskapp-5001
      image: daveyn/devnet:flaskapp5001
      ports:
        - containerPort: 5001
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 300Mi
  imagePullSecrets:
    - name: regcred
