---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-var
data:
  db_url: "db_host.example.com/my_db"
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    role: webapp
spec:
  containers:
    - name: flaskapp
      image: daveyn/devnet:flaskapp3
      env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: db-var
              key: db_url
      ports:
        - containerPort: 5000
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 300Mi
  imagePullSecrets:
    - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  selector:
    role: webapp
