---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    role: webapp
spec:
  containers:
    - name: flaskapp
      image: daveyn/devnet:flaskapp3
      ports:
        - containerPort: 5000
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 300Mi
  imagePullSecrets:
    - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  selector:
    role: webapp
