---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    role: webapp
spec:
  containers:
    - name: flaskapp
      image: daveyn/devnet:flaskapp3
      ports:
        - containerPort: 5000
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 300Mi
  imagePullSecrets:
    - name: regcred
